#.github/workflows/Base-pytest-demo-useaction.yaml
name: Base-pytest-demo-useaction
on: workflow_dispatch
jobs:
  job1:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'python-demo-pytest'
      - name: what path
        run: pwd
      - name: install pytest
        run: pip install pytest
      - name: Run pytest
        run: pytest
