#.github/workflows/Events-Multiple-Events.yaml
name: Multiple Events
on: [push,workflow_dispatch]
jobs:
    job1:
        name: test events
        runs-on: ubuntu-latest
        steps:
            - name: trigger events
              run: echo "triggered by ${{ github.event_name }}"