#.github/workflows/Events-Demo-Pyinstaller.yaml
name: Events-Demo-Pyinstaller
on: workflow_dispatch
jobs:
    job1:
        name: build
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: install pyinstaller
            run: pip install pyinstaller
          - name: Run pyinstaller
            working-directory: python-sha256
            run: pyinstaller sha256.py -F
