#.github/workflows/Events-Demo-Pyinstaller.yaml
name: Events-Demo-Pyinstaller
on: workflow_dispatch
jobs:
    job1:
        name: build
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: what path
            run: |
                cd python-sha256
                pwd
                ls
          - name: install pyinstaller
            run: pip install pyinstaller
          - name: Check file existence
            run: |
                Get-ChildItem -Recurse
          - name: Run pyinstaller
            working-directory: python-sha256
            run: |
                pwd
                Get-ChildItem
                pyinstaller sha256.py -F
