name: pytest-demo
on: workflow_dispatch

jobs:
    job1:
        name: pytest
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              run: |
                git clone https://github.com/Gnauk841026/PlayGround-GitHubAction.git
                cd playGround-GitHubAction/python-demo-pytest

            - name: install pytest
              run: pip install pytest
            - name: Run pytest
              run: pytest
