name: Multi-Job Workflow Example

on: workflow_dispatch

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "This is job 1"

  job2:
    name: Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Run another script
        run: echo "This is job 2"

  job3:
    name: Third Job
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Run final script
        run: echo "This is job 3"
